variable "resource_group_name" {
  type        = string
  description = "Azure Resource Group name"
}

variable "location" {
  type        = string
  description = "Azure region for the SQL Server"
}

variable "project_name" {
  type        = string
  description = "Project name (e.g., gencolink)"
}

variable "environment" {
  type        = string
  description = "Environment (e.g., prod)"
}

variable "admin_username" {
  type        = string
  description = "SQL Server admin username"
}

variable "admin_password" {
  type        = string
  description = "SQL Server admin password (generated by the caller - random_password.sql_admin_password - single source of truth stays in root main.tf)"
  sensitive   = true
}

variable "database_name" {
  type        = string
  description = "SQL Database name"
}

variable "allowed_ip_addresses" {
  type        = list(string)
  description = "Outbound IPs allowed to connect (e.g. the App Service Plan's outbound IPs). Scoped firewall rules instead of the broad AllowAzureServices (0.0.0.0) rule."
  default     = []
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to all resources in this module"
  default     = {}
}
