variable "resource_group_name" {
  type        = string
  description = "Azure Resource Group name"
}

variable "location" {
  type        = string
  description = "Azure region for the SQL Server"
}

variable "project_name" {
  type        = string
  description = "Project name (e.g., gencolink)"
}

variable "environment" {
  type        = string
  description = "Environment (e.g., prod)"
}

variable "admin_username" {
  type        = string
  description = "SQL Server admin username"
}

variable "admin_password" {
  type        = string
  description = "SQL Server admin password (generated by the caller - random_password.sql_admin_password - single source of truth stays in root main.tf)"
  sensitive   = true
}

variable "database_name" {
  type        = string
  description = "SQL Database name"
}

variable "allow_azure_services" {
  type        = bool
  description = "Add the broad 'AllowAllWindowsAzureIps' (0.0.0.0) firewall rule, letting any Azure resource in any tenant attempt a connection (still requires valid credentials). Used only on Free/Shared plan tiers, where VNet integration is unavailable and the App Service's outbound IPs aren't known until after apply (so a precise, IP-scoped rule can't be created in a single terraform apply)."
  default     = false
}

variable "allowed_subnet_ids" {
  type        = list(string)
  description = "Subnet IDs allowed to connect via Microsoft.Sql service endpoint (e.g. the App Service VNet-integration subnet). Used on B1+ tiers - precise, no dependency on mutable outbound IPs."
  default     = []
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to all resources in this module"
  default     = {}
}
