services:
  directus:
    image: directus/directus:10.13.1
    ports:
      - '8055:8055'
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
      - ./extensions:/directus/extensions
      - ./schema:/directus/schema
    env_file:
      - .env
